name: CI/CD

on:
  push:
    branches: [ master ]
    paths: 
      - '**/src/**'
      - '**/pom.xml'
      - '**/Dockerfile'
      - '**/Procfile'
      - '**/system.properties'
  pull_request:
    branches: [ master ]
    paths: 
      - '**/src/**'
      - '**/pom.xml'
      - '**/Dockerfile'
      - '**/Procfile'
      - '**/system.properties'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}:latest
  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
